### Check the lambda handler's health
GET {{baseUrl}}/health
Accept: application/json
Content-Type: application/json


### POST to validate a number
< {%
    request.variables.set("numberToValidate", [ // test data
        4123456789012345, // Visa
        5100000000000000, // Mastercard
        6011456789012345, // Discover
        1011456789012345, // Other
    ])
%}

POST {{baseUrl}}/number
Accept: application/json
Content-Type: application/json

{
  "numberToValidate": {{$.numberToValidate}}
}

### Check the 404 handler
GET {{baseUrl}}/not-a-page

