### Check the lambda handler's health
GET {{baseUrl}}/health
Accept: application/json
Content-Type: application/json


### POST to validate a Visa number
POST {{baseUrl}}/number
Accept: application/json
Content-Type: application/json

{
  "numberToValidate": 4123456789012345
}

### POST to validate a Mastercard number
POST {{baseUrl}}/number
Accept: application/json
Content-Type: application/json

{
  "numberToValidate": 5100000000000000
}

### POST to validate a Discover number
POST {{baseUrl}}/number
Accept: application/json
Content-Type: application/json

{
  "numberToValidate": 6011456789012345
}

### POST to validate a number
POST {{baseUrl}}/number
Accept: application/json
Content-Type: application/json

{
  "numberToValidate": 1011456789012345
}

### Check the 404 handler
GET {{baseUrl}}/not-a-page

